INSERT INTO ECOMP_PRODUCT (PRODUCT_ID, PRODUCT_NM) VALUES
  (1, 'GARMET SHIRT GIORDANO'),
  (2, 'SHOE SNEAKERS NIKE'),
  (3, 'WATCH BAND APPLE');
  
INSERT INTO ECOMP_PROD_CATEGORY (CATEGORY_ID, CATEGORY_NM, DEFUNCT_F) VALUES
  (1, 'GARMET', 'N'),
  (2, 'SHOE', 'N'),
  (3, 'WATCH', 'N');

INSERT INTO ECOMP_PROD_SUB_CATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NM, CATEGORY_ID, DEFUNCT_F) VALUES
  (1, 'GIORDANO', 1, 'N'),
  (2, 'NIKE', 2, 'N'),
  (3, 'APPLE', 3, 'N');

INSERT INTO ECOMP_TAG (TAG_ID, TAG_NM) VALUES
  (1, 'NEW'),
  (2, 'BAND'),
  (3, 'POLO');

INSERT INTO ECOMP_PRODUCT_TAG (PRODUCT_ID, TAG_ID) VALUES
  (1, 1),
  (2, 2),
  (3, 1);

INSERT INTO ECOMP_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_ID) VALUES
  (1, 1),
  (2, 2),
  (3, 1);

INSERT INTO ECOMP_PRODUCT_SUB_CATEGORY (PRODUCT_ID, SUB_CATEGORY_ID) VALUES
  (1, 1),
  (2, 2),
  (3, 3);

